### ISSUE TITLE
Error while installation

### ISSUE THREAD

**Issue by yatishextreme** [Dan-in-CA/SIP#155]
after sudo python sip.py

[0, 0, 0, 0, 0, 0, 0, 0]
http://0.0.0.0:80/
Traceback (most recent call last):
  File "ospi.py", line 236, in <module>
    app.run()
  File "ospi.py", line 170, in run
    return web.httpserver.runsimple(func, ('0.0.0.0', port))
  File "/SIP/web/httpserver.py", line 157, in runsimple
    server.start()
  File "/SIP/web/wsgiserver/__init__.py", line 1753, in start
    raise socket.error(msg)
socket.error: No socket could be created

**Comment by Dan-in-CA** [comment]
This error results when another program is already using port 80.
Be sure no other programs are running such as a web server that uses port 80. Once you have SIP running you can change the port it uses on the options page of the UI.
