### ISSUE TITLE
Internal Server Error accessing "Programs" tab

### ISSUE THREAD

**Issue by kvrenshaw** [Dan-in-CA/SIP#232]
Went to adjust my programs (I have 2) and I now get "internal server error" whenever I go to myhost/vp

Traceback:
sip[19713]: 10.1.1.15:49828 - - [06/Apr/2020 19:16:58] "HTTP/1.1 GET /UPs" - 200 OK
sip[19713]: 10.1.1.15:49830 - - [06/Apr/2020 19:16:58] "HTTP/1.1 GET /static/images/favicon-32x32.png" - 200
sip[19713]: 10.1.1.15:49828 - - [06/Apr/2020 19:17:00] "HTTP/1.1 GET /api/log" - 200 OK
sip[19713]: Traceback (most recent call last):
sip[19713]:   File "/home/sip/SIP/web/application.py", line 289, in process
sip[19713]:     return self.handle()
sip[19713]:   File "/home/sip/SIP/web/application.py", line 280, in handle
sip[19713]:     return self._delegate(fn, self.fvars, args)
sip[19713]:   File "/home/sip/SIP/web/application.py", line 530, in _delegate
sip[19713]:     return handle_class(cls)
sip[19713]:   File "/home/sip/SIP/web/application.py", line 508, in handle_class
sip[19713]:     return tocall(*args)
sip[19713]:   File "/home/sip/SIP/webpages.py", line 496, in GET
sip[19713]:     return template_render.programs()
sip[19713]:   File "/home/sip/SIP/web/template.py", line 1139, in template
sip[19713]:     return self._base(t(*a, **kw))
sip[19713]:   File "/home/sip/SIP/web/template.py", line 986, in __call__
sip[19713]:     return BaseTemplate.__call__(self, *a, **kw)
sip[19713]:   File "/home/sip/SIP/web/template.py", line 897, in __call__
sip[19713]:     return self.t(*a, **kw)
sip[19713]:   File "templates/programs.html", line 138, in __template__
sip[19713]:     $for s in range(8):
sip[19713]: IndexError: list index out of range
sip[19713]: 10.1.1.15:49828 - - [06/Apr/2020 19:17:03] "HTTP/1.1 GET /vp" - 500 Internal Server Error

Latest change was to update to 4.0.23. I tried 4.0.18 and 4.0.3, but they have the same issue. What do I need to do to fix this?

**Comment by kvrenshaw** [comment]
Closing, somehow got an extra station in the options tab. Solution from #132 lead me to set extensions from 1 to 0 and it is working now.
