### ISSUE TITLE
/jc returns "Internal Server Error"

### ISSUE THREAD

**Issue by kq9914** [Dan-in-CA/SIP#237]
http://ip/jc returns "internal server error"

Ran `sip.py` on it's own and get this:

```
Traceback (most recent call last):
  File "/home/pi/SIP/web/application.py", line 289, in process
    return self.handle()
  File "/home/pi/SIP/web/application.py", line 280, in handle
    return self._delegate(fn, self.fvars, args)
  File "/home/pi/SIP/web/application.py", line 530, in _delegate
    return handle_class(cls)
  File "/home/pi/SIP/web/application.py", line 508, in handle_class
    return tocall(*args)
  File "/home/pi/SIP/plugins/mobile_app.py", line 84, in GET
    u"ct": get_cpu_temp(gv.sd[u"tu"]),
TypeError: get_cpu_temp() takes no arguments (1 given)
```
Changed line 84 of `mobile_app.py` from:

`            u"ct": get_cpu_temp(gv.sd[u"tu"]),` 

to

`            u"ct": get_cpu_temp(),`

it now seems to work as expected

**Comment by Dan-in-CA** [comment]
Thanks for this bug fix.
The SIP repo has been updated with your change.

Dan
