### ISSUE TITLE
Weather Based water level plugin

### ISSUE THREAD

**Issue by t4islander** [Dan-in-CA/SIP#262]
I've recently been seeing the following error from the plug in for weather based water levels:

Weather-based water level encountered error:
Traceback (most recent call last):
  File "/home/pi/SIP/plugins/weather_level_adj.py", line 124, in run
    forecast = forecast_info(self, options, today)
  File "/home/pi/SIP/plugins/weather_level_adj.py", line 799, in forecast_info
    new_old_data = json.loads(fd.read())
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

This has been working fine until recently with no changes in code, is this an API issue or something I can resolve in code?

**Comment by Dan-in-CA** [comment]
It looks like the json data returned from OWM is not correct.

**Comment by t4islander** [comment]
Thanks Dan, I rebooted the Pi just as a troubleshooting measure, it's been OK since but based on your feedback sounds like I was just getting malformed data back. All good now, thanks much.
